SET PATH=D:\Program Files\keil4.7\ARM\ARMCC\bin\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\
SET CPU_TYPE=STM32F205VE
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=TOS
SET CPU_CLOCK=0x017D7840
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\main.__i"
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\stm32f10x_it.__i"
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\misc.__i"
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\stm32f10x_flash.__i"
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\stm32f10x_gpio.__i"
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\stm32f10x_rcc.__i"
"D:\Program Files\keil4.7\ARM\ARMCC\bin\ArmCC" --Via ".\obj\stm32f10x_adc.__i"
